#!/usr/bin/python

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OPENSHIFT_SECRETS_FILE = BASE_DIR + '/config/secrets.js.openshift'
DEPLOY_SECRETS_FILE = BASE_DIR + '/config/secrets.js'

os.rename(OPENSHIFT_SECRETS_FILE, DEPLOY_SECRETS_FILE)
